[package]
name = "s_m"
version = "0.1.0"
authors = ["IADG <170088@hotmail.com.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"